### ISSUE TITLE
Combination of filters and includes

### ISSUE THREAD

**Issue by lefloh** [neuland/jade4j#100]
The combination of filters with includes as described on [jade-lang.com][jade] does not seem to work:

Given following templates:

**main.jade**

    :markdown
      # Markdown

    include ./include.jade
    include:markdown ./include.md
    
**include.jade**

    h2 Included
    
**include.md**

    ### Markdown Included
    
    
Following Unit Test should pass:

    public class MardownIncludeTest {

	    @Test
        public void testInclude() throws Exception {
            JadeConfiguration jade = new JadeConfiguration();
            jade.setFilter("markdown", new MarkdownFilter());
            jade.setPrettyPrint(true);
            JadeTemplate template = jade.getTemplate("main.jade");
            String result = jade.renderTemplate(template, Collections.emptyMap());
            assertTrue(result.contains("<h1>")); // rendered Markdown
            assertTrue(result.contains("<h2>")); // included HTML
            assertTrue(result.contains("<h3>")); // included Markdown
        }
	
    }
    
The test fails in the last line. I'm using jade4j version 0.4.3.

 [jade]: http://jade-lang.com/reference/includes/

**Comment by chbloemer** [comment]
Jade4J 1.0.0 produces
```html
<h1>Markdown</h1>
<h2>Included</h2><h3>Markdown Included</h3>
```
JadeJS 1.11 produces
```html
<h1 id="markdown">Markdown</h1>

<h2>Included</h2><h3 id="markdown-included">Markdown Included</h3>
```

The Markdownfilter needs some adjustments.

**Comment by chbloemer** [comment]
Added Testcase issues/100.jade

**Comment by chbloemer** [comment]
I am going to close this one. The original problem is solved. The different markup is an issue of the PegDownProcessor.
