### ISSUE TITLE
mixin definitions are ignored in extension template

### ISSUE THREAD

**Issue by rzara** [neuland/jade4j#104]
Whether directly defined or via an include, mixing definitions are ignored in template extensions.

These fail:

    extends layout
    mixin hello
        p hello
    block content
        +hello

and

    extends layout
    //- include the 'hello' mixin
    include mixing/my_mixin
    block content
        +hello

This construct works with jade.

**Comment by chbloemer** [comment]
Added your Testcase and it works in Version 1.0.0. Please check if it is working for you, too.
