### ISSUE TITLE
Renaming jade -> pug

### ISSUE THREAD

**Issue by domix** [neuland/jade4j#130]
Have you considered rename jade4j as jade will do?

https://github.com/pugjs/jade/issues/2184

**Comment by chbloemer** [comment]
Yes, we did. Maybe there will be a pug4j 2.0 in the future. So it's in line with jade's javascript implementation. That release could also deprecate java 1.6/1.7. But no work has been done yet.

**Comment by chbloemer** [comment]
Fixed with #185

**Comment by chbloemer** [comment]
Done. See https://github.com/neuland/pug4j
