### ISSUE TITLE
String interpolation in attributes string differs from Jade

### ISSUE THREAD

**Issue by erotte** [neuland/jade4j#131]
Hi,

string interpolation in attribute strings seems to differ substantial from the implementation in Jade 1.11.

```
# results from http://jade-lang.com/ 

mixin testMixin()
  h1.test&attributes(attributes)

- var foo = "qux"
- var bar = "quux"
- foobar = "#{foo}-#{bar}"

# v1
+testMixin()(class="#{foobar}") 
# result: <h1 class="test #{foo}-#{bar}"></h1> – Works in jade4j, but not in Jade 

# v2 
+testMixin()(class=foobar)   
# result: <h1 class="test #{foo}-#{bar}"></h1> – Works in jade4j, but not in Jade

# v3
+testMixin()(class="#{foo}-#{bar}")
# result: <h1 class="test qux-quux"></h1>  – Works in Jade, but not in jade4j

```

This is crucial, because there's no version that works in Jade an jade4j simultaneously.
V3 seems to be the only working notation in the current Jade implementation, jade4j needs the syntax of v2.

Please drop me a line if I'm wrong or missed another notation for that purpose.

**Comment by naltatis** [comment]
Hi @erotte,

What's your expected output?
You can not do string interpolation inside of assignments.

Jade.js implements variables in this way:

    - var myVar = <valid js code>

This should work fine:

    - var foobar = foo + "-" + bar
    +testMixin()(class=foobar)

Jade's interpolation only works directly in attribute values and text nodes.

\ naltatis

**Comment by erotte** [comment]
@naltatis ideed, my expectations may have been accidentally influenced by CoffeeScripts` string interpolation. :grin: 
String concatenation should solve my current problem, thanks for the hint!

**Comment by erotte** [comment]
Hm, concatenation of string variables (your example) also doesn't work in jade4J, you have to call .toString() explicitly:

- var foobar = foo.toString() + "-" + bar.toString()

**Comment by naltatis** [comment]
Are you sure that foo and bar really are strings?

**Comment by naltatis** [comment]
@erotte are you using the jade4j > 1.x?
In older versions of jade and jade4j variable declaration is done without (`- var `):

    foobar = foo + "-" + bar

**Comment by chbloemer** [comment]
```jade
mixin testMixin()
  h1.test&attributes(attributes)

- var foo = "qux"
- var bar = "quux"
- var foobar = "#{foo}-#{bar}"
- var foobar2 = foo + "-" + bar
- var foobar3 = foo.toString() + "-" + bar.toString()
- var foobarbaz = "foobarbaz"

+testMixin()(class="#{foobar}")
+testMixin()(class=foobar)
+testMixin()(class="#{foobar2}")
+testMixin()(class=foobar2)
+testMixin()(class="#{foobar3}")
+testMixin()(class=foobar3)
+testMixin()(class="#{foo}-#{bar}")
+testMixin()(class="#{foobarbaz}")
+testMixin()(class=foobarbaz)
```
produces in JadeJS 1.11
```html

<h1 class="test #{foo}-#{bar}"></h1>
<h1 class="test #{foo}-#{bar}"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test foobarbaz"></h1>
<h1 class="test foobarbaz"></h1>
```
in Jade4J
```html
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test qux-quux"></h1>
<h1 class="test foobarbaz"></h1>
<h1 class="test foobarbaz"></h1>
```

The first two Lines should not be possible in Jade4J.

**Comment by chbloemer** [comment]
This is not   an issue. I am closing this.
