### ISSUE TITLE
class attribute not supported

### ISSUE THREAD

**Issue by SADmitry** [neuland/jade4j#132]
`.form-group.row(class={'has-danger': true})`
Will produce on Jade's site proper HTML.

Jade4j produces `class="form-group row {has-danger=true}"`

**Comment by chbloemer** [comment]
With release 1.2.1 this code
```jade
.form-group.row(class={'has-danger': true})
.form-group.row(class={"has-danger": true})
```
produces
```html
<div class="form-group row has-danger"></div>
<div class="form-group row has-danger"></div>
```

Closing this issue.
