### ISSUE TITLE
Resource loaded using the ClasspathTemplateLoader require *.jade extension before they are copied in

### ISSUE THREAD

**Issue by nishtahir** [neuland/jade4j#135]
The problem seems to be caused here. 

```java
@Override
public Reader getReader(String name) throws IOException {
    if(!name.endsWith(suffix))name = name + suffix;
    return new InputStreamReader(Thread.currentThread().getContextClassLoader().getResourceAsStream(name), getEncoding());
}
```
It assumes that all files must have the `*.jade` extension. So files such as `*.css` and `*.js` aren't loaded unless they are appended with `*.jade`

**Comment by chbloemer** [comment]
Added Testcase 135.jade and running all issue Tests also with ClasspathTemplateLoader. Fixed in release 1.2.0
