### ISSUE TITLE
Jade4J does not support unbuffered code blocks

### ISSUE THREAD

**Issue by Ribesg** [neuland/jade4j#141]
As stated [here](http://jade-lang.com/reference/code/), Jade supports the following syntax:
````jade
-
  var tmp = 12
h1= tmp
````
This syntax works on http://jade-lang.com/demo/ but not on http://naltatis.github.io/jade-syntax-docs/, and not in my project (Using SparkJava with Jade templating implemented with Jade4J).

**Comment by chbloemer** [comment]
Fixed in 1.2.4
