### ISSUE TITLE
Problem With ACL Import

### ISSUE THREAD

**Issue by ZakiaSalod** [neuland/jade4j#149]
Hi All,

My JAVA program cannot resolve the following import, although I have added the jade.jar and commons-codec.jar in my JAVA program class-paths >>>
import jade.lang.acl.ACLMessage;

Please help.
Thanks,
Zakia

**Comment by fabiangr** [comment]
I think you might be referring to the "JAVA Agent DEvelopment Framework" (https://jade.tilab.com/) which is a different project than this.
