### ISSUE TITLE
using .pug extension

### ISSUE THREAD

**Issue by samogot** [neuland/jade4j#154]
Using .pug extension is impossible. Even using spring-jade4j suffix=`.pug`. 
If I request files without extension - `.jage` is forced by `ensureJadeExtension`
If I request files with explicit `.pug` extension - includes interpret it as plain text without parsing because of https://github.com/neuland/jade4j/blob/master/src/main/java/de/neuland/jade4j/parser/Parser.java#L387

**Comment by chbloemer** [comment]
Fixed in 1.2.6
