### ISSUE TITLE
How to prepend web application context root to URLs

### ISSUE THREAD

**Issue by manish-in-java** [neuland/jade4j#159]
The following code does not work if a web application has not been deployed to the root context root (`/`).

    script(src="/script/main.js", type="text/javascript")

This is because this translates to the following HTML code:

    <script src="/script/main.js" type="text/javascript"></script>

Since the application is not deployed to the root context root, `/script/main.js` cannot be found and hence the resource does not load. There should be some way to prepend the context root to URLs so that resources load correctly.

And no, manually coding URLs with the context root is not a solution because the context root could be different in different environments.

**Comment by naltatis** [comment]
You can achieve this using helpers or prepare your model data before passing them into the template.

**Comment by manish-in-java** [comment]
@naltatis, the context root is not model data, it is an intrinsic property of a Java web application. It does not make sense to pass it as a model object into the template. The point should not be how easy or difficult it is to do something but rather that something that is common to all applications should be within the framework itself for it to be widely usable.

Something like `script(src="@{/script/main.js}")` is important to use Jade4J in a large web application. All other web templating engines have support for something like this.

**Comment by naltatis** [comment]
I get your point, but jade does not have a concept of implicit globales / context other than the model data that's put into the template. The main design goal by writing jade4j is to maintain compatibility with the original language. So we won't add new syntax features unless jade/pug does.

When it comes to integration with specific web frameworks "model defaults" can be used by the integration library to make common values available in every template. See the spring-jade4j project for reference.

**Comment by manish-in-java** [comment]
@naltatis, fair enough to maintain compatibility with Jade. I will check the spring-jade4j repository and submit pull requests there.

**Comment by manish-in-java** [comment]
@naltatis, fair enough to maintain compatibility with Jade. I will check the spring-jade4j repository and submit pull requests there.
