### ISSUE TITLE
How to get loop index?

### ISSUE THREAD

**Issue by manish-in-java** [neuland/jade4j#160]
Consider the following code:

    table
      thead
        tr
          th S.No.
          th Name
      tbody
        for person in persons
          tr
            td ?
            td person.name

In the code above I would like to display the record number instead of the question mark (`?`). Is this possible? If yes, how? If not, can this support be added?

**Comment by naltatis** [comment]
Please see the jade/pug syntax for this. Jade4j is "just" a java implementation of the language.

https://naltatis.github.io/jade-syntax-docs/#for

**Comment by manish-in-java** [comment]
Thanks, got it. Please feel free to close this issue.

**Comment by manish-in-java** [comment]
Thanks, got it. Please feel free to close this issue.
