### ISSUE TITLE
where is project com.googlecode.concurrentlinkedhashmap

### ISSUE THREAD

**Issue by uptimestar** [neuland/jade4j#162]
I can find it in maven. But where is the project home page/repo?

**Comment by ben-manes** [comment]
It was moved to Github when Google Code shutdown. See [ben-manes/concurrentlinkedhashmap](https://github.com/ben-manes/concurrentlinkedhashmap).

Note that the project was superseded by [Caffeine](https://github.com/ben-manes/caffeine).

**Comment by uptimestar** [comment]
Thx Ben. Btw nice project. Let me know if you need help updating to 'current' - should not be hard.

**Comment by ben-manes** [comment]
Yes, please upgrade to the `1.4.x` release for improved performance (no API changes). Consider moving towards Caffeine for a better eviction policy and advanced features (but fatter jar dependency).
