### ISSUE TITLE
bump a master release

### ISSUE THREAD

**Issue by uptimestar** [neuland/jade4j#168]
Can we have a new release of master plz?
It uses new flexmakr libs (same as jbake).

Also this folder can now be deleted in master, it is 4 years old.
jade4j/tree/master/releases/de/neuland/jade4j

**Comment by chbloemer** [comment]
jade4j/tree/master/releases/de/neuland/jade4j has been deleted.
new master will be released with 1.2.8
new flexmakr libs will come with pug4j 2, because it raised compiler level to java 1.8+
