### ISSUE TITLE
Pug 2 support

### ISSUE THREAD

**Issue by jirikaiser-atypon** [neuland/jade4j#169]
Does the latest version (1.2.6) support Pug 2?

**Comment by chbloemer** [comment]
It supports the latest jade version. It is not tested against pug 2. If the syntax didn't change a lot from jade to pug, it may support it. We changed jade4j in the latest version to support different file extensions. So you can use pug file extension.

**Comment by chbloemer** [comment]
Done. See https://github.com/neuland/pug4j
