### ISSUE TITLE
Bug with configuring base path

### ISSUE THREAD

**Issue by tskillian** [neuland/jade4j#170]
If the books template is in some/path/, then this will still fail because it doesn't look in the right place:

` JadeConfiguration jadeConfiguration = new JadeConfiguration();
    jadeConfiguration.setBasePath("some/path/");
JadeTemplate template = jadeConfiguration.getTemplate("books");`

This doesn't work because the TemplateLoader gets instantiated without a folder path. The only workaround seems to be to use setTemplateLoader on the configuration yourself. But at that point what's the point of setting a base path?

**Comment by chbloemer** [comment]
Fixed in 1.2.8
