### ISSUE TITLE
Variables defined inside jade templates are not evaluated

### ISSUE THREAD

**Issue by kul** [neuland/jade4j#32]
For instance this fails with,
WARN jexl2.JexlEngine: de.neuland.jade4j.expression.ExpressionHandler.evaluateExpression@28![0,4]: 'name;' undefined variable name

!!! 5
html
  head
    title my jade
  body
    - var name='IronMan'
    h1 Hello #{name}

it would be really nice if this could be added, I already see support for template inheritance , block etc.

Thanks

**Comment by thar0x29a** [comment]
````
- var siteTitle = "My Cool Website";

doctype html
html
  head
    title= siteTitle
````

Works on online pug tools, but refuses to fill on jade4j. Title stays empty
