### ISSUE TITLE
Plain Text newline?

### ISSUE THREAD

**Issue by abonstu** [neuland/jade4j#43]
Is there a way to include newline characters in plain text output?

example:
| hello
| world

should produce (in plain text):
hello
world

but seems to produce:
helloworld

according to the Jade docs newline characters should be preserved in the rendered output:
http://naltatis.github.io/jade-syntax-docs/#text

Note: this occurs even with pretty print enabled.

**Comment by chbloemer** [comment]
Added testcase issues/43.jade. Seems to work in Version 1.0.0.
