### ISSUE TITLE
Potential indentation issue

### ISSUE THREAD

**Issue by ebordeau** [neuland/jade4j#60]
I'm not sure if this is a bug or just me doing something wrong. I have a Jade template that uses tabs and I've verified that there are no spaces. The first line is not indented at all. When the template gets parsed, I get an error: 

class de.neuland.jade4j.exceptions.JadeLexerException layout:3
invalid indentation; expecting 0 spaces
    at de.neuland.jade4j.lexer.Lexer.indent(Lexer.java:652)
    at de.neuland.jade4j.lexer.Lexer.next(Lexer.java:152)
    at de.neuland.jade4j.lexer.Lexer.lookahead(Lexer.java:192)
    at de.neuland.jade4j.parser.Parser.lookahead(Parser.java:726)
    at de.neuland.jade4j.parser.Parser.parseTag(Parser.java:462)
    at de.neuland.jade4j.parser.Parser.parseExpr(Parser.java:116)
    at de.neuland.jade4j.parser.Parser.parse(Parser.java:97)
    at de.neuland.jade4j.parser.Parser.parse(Parser.java:105)
    at de.neuland.jade4j.JadeConfiguration.createTemplate(JadeConfiguration.java:88)
    at de.neuland.jade4j.JadeConfiguration.getTemplate(JadeConfiguration.java:60)

**Comment by SakthiSureshAnand** [comment]
Guys please help I am also facing The same issue but I dont Have Much knowledge on Jade coding , I posted My question and error in stack over flow community please walk on that and help Me, Please I am trying to solve more 4 fours

**Comment by SakthiSureshAnand** [comment]
I pointed there when the error came I just include four lined before `.panel footer`  , It created this error . Please guide me guys ,

**Comment by SakthiSureshAnand** [comment]
My jade code is 
`.row
    .col-md-12
        .panel.panel-primary
            .panel-heading
                h3 {{cc.header.subject}}
                ep-editable-date-time(model='cc.header')
            .panel-body
                .panel.panel-default(ng-repeat='step in cc.checklist.steps',
                data-step='{{step.stepPath[step.stepPath.length - 1].name}}')
                    .panel-heading
                        span.pull-right.checklist-controls(ng-if='cc.checkupType !== cc.types.DRIVEBY')
                            button.btn(ng-class="{'active': !step.skip, 'btn-default': step.skip, 'btn-success':!step.skip}",
                            ng-click='step.skip=!step.skip; step.skip ? step.noSelfCheckNeeded=true : noop')
                                span Include
                                    =" "
                                span.fa(ng-class="{'fa-square-o': step.skip, 'fa-check-square-o': !step.skip}")
                            =" "
                            span(ng-if='cc.checkupType === cc.types.SUPERVISOR')
                                button.btn(ng-class="{'active': !step.noSelfCheckNeeded, 'btn-success': !step.noSelfCheckNeeded, 'btn-default':step.noSelfCheckNeeded}",
                                ng-click='step.noSelfCheckNeeded=!step.noSelfCheckNeeded',
                                ng-disabled='step.skip')
                                    span Self Check
                                        =" "
                                    span.fa(ng-class="{'fa-check-square-o':!step.noSelfCheckNeeded, 'fa-square-o': step.noSelfCheckNeeded}")
                        h5.checklist-header(ng-bind='step.process.name')
                        h6
                            span(ng-repeat='s in step.stepPath')
                                span(ng-bind='s.name')
                                span(ng-show='!$last')
                                    =" > "
                    table.table
                        col
                        col(style='width: 60px')
                        thead
                            tr
                                th(colspan='2', style='text-align: right') In compliance?
                                th(style='width: 100px') Not-Applicable
                        tbody
                            tr(ng-repeat='b in step.behaviors')
                                td(ng-bind='b.name')
                                td
                                    span.bigcheck.compliance-checkbox
                                        label.bigcheck
                                            input.bigcheck(type='checkbox', ng-model='b.compliance', ng-disabled='step.skip')
                                            span.bigcheck-target
//I added these lines which started and ended with ** , It makes me a trouble please guided any one what I have missed ., 
                                **td
                                    span.bigcheck.compliance-checkbox
                                        label.bigcheck
                                            input.bigcheck(type='checkbox', ng-model='b.compliance', ng-disabled='step.skip')
                                            span.bigcheck-target**                                                        
            .panel-footer
                div(ng-if='cc.checkupType === cc.types.SUPERVISOR', style='text-align: center')
                    span(ng-if='!cc.selfCheckupNeeded()')
                        h6(ng-if='cc.anyStepsSelected()') Save and Return to Subject Dashboard
                        h6(ng-if='!cc.anyStepsSelected()') Include at least one Step before saving Checkups
                        button.btn.btn-success(ng-if='!cc.selfCheckupNeeded()',
                        ng-disabled='!cc.isCheckupDTValid() || !cc.anyStepsSelected()',
                        ng-click='cc.saveAndDontSelfCheckup()') Save Supervisor Checkup
                    span(ng-if='cc.selfCheckupNeeded()')
                        h6 Save and Start Self Checkup
                        button.btn.btn-primary.self-checkup-now-btn(ng-disabled='!cc.isCheckupDTValid()',
                        ng-click='cc.saveAndStartSelfCheckup()')
                            span.fa.fa-check-square-o
                            |  Self Checkup Now
                        =" "
                        button.btn.btn-danger.self-checkup-later-btn(ng-disabled='!cc.isCheckupDTValid()', ng-click='cc.saveAndSelfCheckupLater()')
                            span.fa.fa-check-square-o
                            |  Self Checkup Later
                div(ng-if='cc.checkupType === cc.types.SELF', style='text-align: center')
                    h6 Save and View Results
                    button.btn.btn-success.save-self-checkup(ng-disabled='!cc.isCheckupDTValid()',
                    ng-click='cc.saveAndDontSelfCheckup()')
                        span.fa.fa-check-square-o
                        |  Save Self Checkup
                div(ng-if='cc.checkupType === cc.types.DRIVEBY', style='text-align: center')
                    h6 Save Checkup
                    button.btn.btn-success(ng-disabled='!cc.isCheckupDTValid()', ng-click='cc.saveAndDontSelfCheckup()')
                        span.fa.fa-check-square-o
                        |  Save Checkup`

Error is 
`org.springframework.web.util.NestedServletException: Request processing failed; nested exception is class de.neuland.jade4j.exceptions.JadeLexerException checkup/checklist.jade:42
invalid indentation; expecting 0 spaces
Caused by: de.neuland.jade4j.exceptions.JadeLexerException: invalid indentation; expecting 0 spaces`

Please guide me guys
