### ISSUE TITLE
XML encoding for special character does not work

### ISSUE THREAD

**Issue by siddhartharoy** [neuland/jade4j#65]
Hi,

We are using Jade4j in our project both for HTML and XML generation. For XML generation, I have set the JadeTemplate mode to Jade4J.Mode.XML. But generated XML encodes special characters with HTML entity reference which XML parser does not understand. For e.g., Ch. & de la Mêlée 12 becomes "Ch. &amp; de la M&ecirc;l&eacute;e 12". &ecirc; and &eacute; are fine to HTML perspective but not XML.

I had downloaded the jade4j code to understand the problem and found even though we are setting the mode to XML but not used in the code. Utils.interpolate(List<Object> prepared, JadeModel model) method always uses StringEscapeUtils.escapeHtml4 to encode value. 

Can you please fix this (OR) please let me know if I am missing something.

Thanks and lot.

Rgds - Sidd

**Comment by graeme-lockley** [comment]
Hi,

We're having the same problem.  Sidd have you found a workaround for this problem?

Many thanks,
  Graeme

**Comment by chbloemer** [comment]
```jade
doctype xml
p
    |Ch. & de la Mêlée 12
```
generates 
```html
<?xml version="1.0" encoding="utf-8" ?>
<p>Ch. & de la Mêlée 12</p>
```
in jadejs (pugjs) and jade4j. If their is an issue it should be fixed in the javascript version, too.
