### ISSUE TITLE
jade4j compilation issue

### ISSUE THREAD

**Issue by siddhartharoy** [neuland/jade4j#67]
Hi,

Environment: Windows 7.

I have downloaded jade4j code. But when I build the code even without change "de.neuland.jade4j.compiler.OriginalJadeTest" test case fails with error

Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2.

Rgds - Sidd

**Comment by IRus** [comment]
Looks like the same issue as #9

**Comment by IRus** [comment]
I try run tests on my Ubuntu machine with Oracle Java 8 and some tests also fail.

I try to figurare out what the problem with ```JadeRunFullTemplateTest``` and found problem: project works well with java 7, but fails on java 8

**Comment by IRus** [comment]
Failed tests:   
* testEachLoopWithIterableMap(de.neuland.jade4j.template.JadeRunFullTemplateTest): ```expected:<<ul><li>[Robert Smith</li><li>Alex Supertramp]</li></ul>> but was:<<ul><li>[Alex Supertramp</li><li>Robert Smith]</li></ul>>```
* attribute(de.neuland.jade4j.compiler.CompilerTest): attribute ```expected:<..." data-a="b"></p><p [hello="worl'd" a="c]"></p><input checked...> but was:<..." data-a="b"></p><p [a="c" hello="worl'd]"></p><input checked...>```
* tagWithAttributes(de.neuland.jade4j.compiler.CompilerTest): tags_with_attributes ```expected:<...div class="myclass" [title="my first div" alt="alt does not fit here]"><div class="c1 c2 ...> but was:<...div class="myclass" [alt="alt does not fit here" title="my first div]"><div class="c1 c2 ...>```
* mixinAttrs(de.neuland.jade4j.compiler.CompilerTest): mixin_attrs ```expected:<...ss="bottom foo bar" [id="Last" data-attr="baz" name="end]">(..)```
* mixinVariableAttribute(de.neuland.jade4j.compiler.CompilerTest): mixin_variable_attribute ```expected:<<a [class="abc" href="/foo]">foo</a>> but was:<<a [href="/foo" class="abc]">foo</a>>```
* test(de.neuland.jade4j.compiler.OriginalJadeTest): html5.jade ```expected:<...DOCTYPE html><input [type="checkbox" checked><input type="checkbox" checked]><input type="checkb...> but was:<...DOCTYPE html><input [checked type="checkbox"><input checked type="checkbox"]><input type="checkb...>```

Tests run: 120, Failures: 6, Errors: 0, Skipped: 0

**Comment by IRus** [comment]
https://travis-ci.org/IRus/jade4j/builds/57734270
Example build

**Comment by IRus** [comment]
Build on CI: https://travis-ci.org/IRus/jade4j/builds/57764072

**Comment by IRus** [comment]
@siddhartharoy @dstaas Hello! Please pull latest version and check if you still have this issue.

**Comment by chbloemer** [comment]
Is this still an issue?

**Comment by IRus** [comment]
@chbloemer it's not for me.

**Comment by chbloemer** [comment]
Ok, then I close this issue.
