### ISSUE TITLE
If not recognizing when trying to find first entry

### ISSUE THREAD

**Issue by jrgleason** [neuland/jade4j#73]
I am trying to do something like this...

http://stackoverflow.com/questions/10004079/jade-template-engine-each-iteration-offset

I used this code...

  each crumb, i in crumbs
      if i == 1
        a(href="#{crumb.url}")
          span.me-home
          #{crumb.name}
      else
        a(href="#{crumb.url}")

But no dice it is always false and the js style equals (===) also doesn't seem to be working.

**Comment by chbloemer** [comment]
This code:
```jade
-var crumbs = [{"url":"http://www.xyz.com","name":"xyz"},{"url":"http://www.abc.com","name":"abc"}]
each crumb, i in crumbs
    if i == 1
        a(href="#{crumb.url}")
            span.me-home
                #{crumb.name}
    else
        a(href="#{crumb.url}")
```
produces:
```html
<a href="http://www.xyz.com"></a><a href="http://www.abc.com"><span class="me-home">
    <abc></abc></span></a>
```

The same as in jade 1.11.

I am closing this issue.
