### ISSUE TITLE
Jade4J is putting GSP include in body instead of head. 

### ISSUE THREAD

**Issue by jrgleason** [neuland/jade4j#74]
I have a gsp with the following 

```
<g:javascript library="jquery"/>
<r:require module="meBootstrap"/>
```

I try to include it in my head.jade

```
...
title=title
include ../layouts/_head.gsp
```

And then include that in my layout.jade

```
html
  head
    include head
```

but it goes into the body so the rendered html look like...

```
<body>
<g:javascript library="jquery">
<r:require module="meBootstrap">
...
</r:require>
</g:javascript>
</body>
```

The title and everything in jade is working as expected

This is using grails 2.3.7

I will try to look into these eventually but for now any direction on where in the Jade4J code to look would be great :-)

**Comment by chbloemer** [comment]
Added Testcase issues/74.jade. It works in Version 1.0.0.
