### ISSUE TITLE
ExpressionString cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by dstaas** [neuland/jade4j#76]
When one template "extends" another, I get the following error.  I forked to attempt a fix but there are 6 unit tests failing (before I changed anything) so I am hesitant to try to fix it until the tests are OK.  Please let me know if there's anything I can do to help, and thank you for all your work on this project.

		java.lang.ClassCastException: de.neuland.jade4j.parser.node.ExpressionString cannot be cast to java.lang.String
		de.neuland.jade4j.parser.node.AttributedNode.getAttribute(AttributedNode.java:26)
		de.neuland.jade4j.parser.Parser.parseTag(Parser.java:534)
		de.neuland.jade4j.parser.Parser.parseExpr(Parser.java:116)
		de.neuland.jade4j.parser.Parser.parse(Parser.java:97)
		de.neuland.jade4j.parser.Parser.parseInclude(Parser.java:310)
		de.neuland.jade4j.parser.Parser.parseExpr(Parser.java:131)
		de.neuland.jade4j.parser.Parser.block(Parser.java:382)
		de.neuland.jade4j.parser.Parser.parseTag(Parser.java:549)
		de.neuland.jade4j.parser.Parser.parseExpr(Parser.java:116)
		de.neuland.jade4j.parser.Parser.block(Parser.java:382)
		de.neuland.jade4j.parser.Parser.parseTag(Parser.java:549)
		de.neuland.jade4j.parser.Parser.parseExpr(Parser.java:116)
		de.neuland.jade4j.parser.Parser.parse(Parser.java:97)
		de.neuland.jade4j.parser.Parser.parseInclude(Parser.java:310)
		de.neuland.jade4j.parser.Parser.parseExpr(Parser.java:131)
		de.neuland.jade4j.parser.Parser.block(Parser.java:382)
		de.neuland.jade4j.parser.Parser.parseCode(Parser.java:665)
		de.neuland.jade4j.parser.Parser.parseExpr(Parser.java:164)
		de.neuland.jade4j.parser.Parser.parse(Parser.java:97)
		de.neuland.jade4j.parser.Parser.parse(Parser.java:105)
		de.neuland.jade4j.Jade4J.createTemplate(Jade4J.java:95)
		de.neuland.jade4j.Jade4J.getTemplate(Jade4J.java:86)
		de.neuland.jade4j.Jade4J.render(Jade4J.java:32)
		de.neuland.jade4j.Jade4J.render(Jade4J.java:28)
		com.hp.sms.sample.SampleRest.getBooks(SampleRest.java:41)
		sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		java.lang.reflect.Method.invoke(Unknown Source)
		org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
		org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:269)
		org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:227)
		org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:216)
		org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:542)
		org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
		org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:126)
		org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208)
		org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
		org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
		javax.servlet.http.HttpServlet.service(HttpServlet.java:722)

**Comment by chbloemer** [comment]
Please provide a testcase. You can also test if it's working in Version 1.0.0.

**Comment by chbloemer** [comment]
Closing this. If there is still an issue, please feel free to reopen this issue with example code.
