### ISSUE TITLE
Incorrect rendering of backslashes in attribute values

### ISSUE THREAD

**Issue by kamituel** [neuland/jade4j#78]
Consider this template:

`
input(ng-pattern='/\\s+/')
`

Original (Node.js') Jade implementation would compile it to:

`
<input ng-pattern="/\s+/"/>
`

While Jade4J compiles it to:

`
<input ng-pattern="/\\s+/">
`

**Comment by chbloemer** [comment]
Added Testcase issues/78.jade. It's currently not working in Version 1.0.0. The toConstant method from jadejs needs to be ported to Jade4J.

**Comment by chbloemer** [comment]
Fixed in jade4j 1.2.2
