### ISSUE TITLE
No way to use "attributes" attribute

### ISSUE THREAD

**Issue by Draivin** [neuland/jade4j#81]
When using the polymer library, you use an attribute called `attributes` to allow external binding to the element, but in jade4j, `attributes` is a variable used for accessing mixin attributes.

This code:
```jade
    div(attributes="test")
```
should compile to (and does so in jade):
```html
    <div attributes="test"></div>
```
but in jade4j it compiles to:
```html
    <div></div>
```
A simple fix would be checking if the `attributes` attribute has a value assigned to it, and if so treat it like a normal attribute.

**Comment by waldemar-schneider** [comment]
Is there any progress in this issue? Sometimes it is very useful to use an array of classes instead of hardcoded classes in jade.

**Comment by chbloemer** [comment]
Added Testcase issues/81.jade. In Version 1.0.0 it works.
