### ISSUE TITLE
order of attributes is different sometimes

### ISSUE THREAD

**Issue by waldemar-schneider** [neuland/jade4j#86]
On my local setup (MacOS), IntelliJ IDEA, Java 8, some tests are failing because the order of some attributes are different.

For example the test `de.neuland.jade4j.compiler.CompilerTest#mixinVariableAttribute` is failing with the following message:

```
org.junit.ComparisonFailure: mixin_variable_attribute 
Expected :<a class="abc" href="/foo">foo</a>
Actual   :<a href="/foo" class="abc">foo</a>
```

It seems that `de.neuland.jade4j.lexer.token.Attribute`-class stores the attributes (the name is somehow confusing) in a hashmap. It should be something like a linkedhashmap or a similiar implementation which keeps the order of the insertion.

**Comment by IRus** [comment]
@waldemar-schneider looks like this issue should be closed.
