### ISSUE TITLE
Can't build on Windows 

### ISSUE THREAD

**Issue by michaelkrog** [neuland/jade4j#9]
I tried to build it on a windows computer, but the tests fails. 
**This is not an issue for me, but I just wanted to post it anyway.**

It seems that the code relies somewhat on unix-paths - especially the ability to 1) concatenate 2 paths and 2) use the path directly in a URI.create() call.

**1)**
Concatenating windows paths become stuff like 'C:\folder\folder\C:\folder\folder\folder\file

**2)**
URI.create does not like uri's like 'C:\folder\file' unless it is prepended with something like 'file:/' resulting in file:/C:/folder/file

I tried on windows XP with JDK 1.6.24.

**Comment by kayr** [comment]
I partially faced the same issue on windows..

If I use `Jade4J.render("c:/path/to/file.jade", model)` it works.. but `include ...` statements do not work 

Also `Jade4J.render("file:/c:/path/to/file"..` works... but `include ...` statements do not work.

Workaround:
Use `Jade4J.render("/C:/path/to/file.jade"...`: This worked for me on v1.2.3 :)

**Comment by chbloemer** [comment]
What about Jade 1.2.4? I made Changes to the "Uri.create" part of the code. I currently don't have a Windows machine available to test that.

**Comment by kayr** [comment]
Hi,

Thanx for the update.. here are the results of my testing:

 `Jade4J.render("c:/path/to/file.jade", model)` it works.. great :+1: 

`Jade4J.render("/C:/path/to/file.jade"...:` This also works :+1: 

Also `Jade4J.render("file:/c:/path/to/file"..` this does not work at all now. I get this Exception `java.io.FileNotFoundException: file:path/to/file.jade (The filename, directory name, or volume label syntax is incorrect)`. Am not sure how many people use this protocol like syntax am just mentioning it for completeness sake since it worked before, but this is not an issue for me

**Comment by chbloemer** [comment]
Thx for your tests. What about 1.2.5.
Does mvn install work correct on windows now?

**Comment by kayr** [comment]
It almost builds.. Some tests fail due line separator issues now.
The html files in the repo use `LF` yet windows uses `CRLF`. So the `assertEquals` fails because the difference in line separators.

Also `PathHelperTest.shouldResolvePathWindows()` fails on a path separator issue. Here is the output
```
Expected :C:/_layout.jade
Actual   :C:\_layout.jade
```

**Comment by chbloemer** [comment]
This should be fixed in Master.

**Comment by kayr** [comment]
Thanx for working on this,

All tests now pass in the IDE :+1:  . However some were failing with `mvn clean install` am not sure why. However doing a minor edit in the file reader to use `UTF-8` explicitly made `mvn clean install`. (see pull request neuland/jade4j#148 ). 

On a side note(might be helpful to others):
To fix the new line issues...I had to turn off git line ending normalization (see.. http://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows)

**Comment by fabiangr** [comment]
The build runs fine using `mvn install` on Windows 10 with Oracle JDK 8 and Maven 3.6.2.
