### ISSUE TITLE
Jade compiler exception on strings containing comma

### ISSUE THREAD

**Issue by dusanmsk** [neuland/jade4j#90]
I get jade compiler exception when calling method with string parameter containing comma (,) charracter:

Jade Compiler Exception - unable to evaluate ['a] - Tokenization de.neuland.jade4j.expression.ExpressionHandler.evaluateExpression@1:3 tokenization error in ''a'

Try to compile following example:

<pre>
mixin test(text)
      div= text

    mixin test('a,b')
</pre>

version: 0.4.0

Thx for fix.

**Comment by dusanmsk** [comment]
I found that for this concrete example, problem is a method:

	public void setArguments(String arguments) {
		this.arguments.clear();
		for (String argument : arguments.split(",")) {
			this.arguments.add(argument.trim());
		}
	}

But (maybe) I simplified the example too much - the primary place where I found this problem was a method call:

mixin hint(l10n.tr('This sentence, contains a comma'))

so it should be much more generic (bad argument parsing).

**Comment by dusanmsk** [comment]
I've tried to fix it myself, please see pull rq https://github.com/neuland/jade4j/pull/91

**Comment by waldemar-schneider** [comment]
Hi @dusanmsk 

can you provide a test in which you show the error in the current version?

**Comment by marlonbernardes** [comment]
@dusanmsk Ive added some comments to your PR.

**Comment by dusanmsk** [comment]
@waldemar-schneider here is the example on 0.4.2: https://drive.google.com/file/d/0ByXboA6FynpJVzY0QmJETzJkb3c/view?usp=sharing

Run main() method on JadeTest class and see test.jade file for my usecase.

**Comment by waldemar-schneider** [comment]
Actually i thought it will be more useful if the testcase is part of the tests. If you look at the test packages, there are allready some static jade files and the expected html snippet. Just put your jade and html (the expected format) file into the directory:
> src/test/resources/compiler

**Comment by dusanmsk** [comment]
@waldemar-schneider Ok, but how I inject a class by json into model map?

**Comment by dusanmsk** [comment]
Added few tests directly to CompilerTest test

**Comment by waldemar-schneider** [comment]
Sorry for the late response. Your added tests are looking good.

**Comment by FinalGuy** [comment]
@waldemar-schneider, @dusanmsk  Is this issue fixed?

**Comment by dusanmsk** [comment]
As it still seems not to be merged, no.

**Comment by FinalGuy** [comment]
Ok, i'll have a look at it. Thank you for responding so fast.

**Comment by FinalGuy** [comment]
Pull Request https://github.com/neuland/jade4j/pull/91 is merged in release 0.4.3. Thanks everybody for your time and effort.

**Comment by theamazinghari** [comment]
still happen
