### ISSUE TITLE
is comma not optional in the attribute list?

### ISSUE THREAD

**Issue by ralemy** [neuland/jade4j#96]
according to the demo site, http://naltatis.github.io/jade-syntax-docs/, comma between attributes is optional, so something like this should be valid:
a(href="#" name="blue")
but when I try it, I get an exception:
de.neuland.jade4j.exceptions.ExpressionException: unable to evaluate ["#" name="blue"] - Parsing "blue"@1:43 parsing error near '... en express ...'
	at de.neuland.jade4j.expression.ExpressionHandler.evaluateExpression

unless I add a comma between the attributes like this a(href="#", name="blue")

Is this intended behavior, or am I doing something wrong?
Cheers,
Reza

**Comment by naltatis** [comment]
The optional coma in jade.js is quite new. We should definitely support this.

**Comment by naltatis** [comment]
Here is the commit that added commaless attributes for original jade.
https://github.com/jadejs/jade/commit/3c03336cf98fc8f9e8e90782e5bed8bd90ca6a54
Would be quite a rewrite of [AttributeLexer](https://github.com/neuland/jade4j/blob/master/src/main/java/de/neuland/jade4j/lexer/AttributeLexer.java).

**Comment by ralemy** [comment]
Wow. you are right. I had thought just adding a case '  ': between lines 45 and 46 of the AttributeLexer would do the trick...

**Comment by crowmagnumb** [comment]
Is this idea dead? I keep running into this problem, especially when I copy and paste from html before jadifying.

**Comment by naltatis** [comment]
No this is definitly an important feature that should be done to get compatibility to the newer jade.js releases. Pull requests are very welcome :)

**Comment by crowmagnumb** [comment]
Ha! Well I'll see how much time I can squeeze in for that.  ;) You do seem to have a full set of tests to make sure things don't go haywire.

**Comment by naltatis** [comment]
Sounds promising :) Yes have quite good test coverage. Feel free to ask if I can help out.

**Comment by chbloemer** [comment]
It should be fixed in Version 1.0.0. Please try it out.

**Comment by crowmagnumb** [comment]
Sweet. Works a charm. Thanks!!
