### ISSUE TITLE
Tag Interpolation Feature

### ISSUE THREAD

**Issue by larsonjj** [neuland/jade4j#97]
In the newer versions of Jade (Node), there is the ability to do [tag interpolation](http://jade-lang.com/reference/interpolation/) that doesn't seem to work within Jade4J.

Ex:
Jade
```jade
p.
  A #[a(href="#") Link]
```

Expected HTML:
```html
<p>A <a href="#">Link</a></p>

```

**Comment by devlato** [comment]
I have faced the same issue, this feature is required pretty much.

**Comment by chbloemer** [comment]
Added Testcase issues/97.jade. It works in Version 1.0.0.
