### ISSUE TITLE
XML encoding for special character does not work properly

### ISSUE THREAD

**Issue by siddharthasroy** [neuland/jade4j#98]
XML encoding for special character like é does not work properly. It always gets escaped as &eacute; which is valid HTML escape but not XML. This happens even after setting the mode as XML.

**Comment by chbloemer** [comment]
The code
```jade
doctype xml
summary
    éáú
```
produces
```html
<?xml version="1.0" encoding="utf-8" ?>
<summary>éáú</summary>
```
in jade4j 1.2.0.

Thats the same as in jade 1.11. So I see no issue and I am closing this. If this is an issue of jade itself open an issue in the jadejs issue tracker.
