### ISSUE TITLE
Can not render success by using the example in  README.md file

### ISSUE THREAD

**Issue by fengcj** [neuland/jade4j#99]
Hi, I try to use jade4j by using the exmaple in README.md file, below is the code:

	public static String returnJadeTemplate() throws Exception {
		
		class Book {
			String name;
			double price;
			Boolean available;

			public Book(String name, double price, Boolean available) {
				this.name = name;
				this.price = price;
				this.available = available;
			}
		}

		String html = null;

		List<Book> books = new ArrayList<Book>();
		books.add(new Book("The Hitchhikers Guide to the Galaxy", 5.70, true));
		books.add(new Book("Life, the Universe and Everything", 5.60, false));
		books.add(new Book("The Restaurant at the End of the Universe", 5.40,
				true));

		Map<String, Object> model = new HashMap<String, Object>();
		model.put("books", books);
		model.put("pageName", "My Bookshelf");	
		
		try {
				html = Jade4J.render("index.jade", model);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return html;		
	}

and the result is below:

![image](https://cloud.githubusercontent.com/assets/3964458/9109089/9c318e34-3c65-11e5-85bd-a0f3bb0b08b5.png)

this means the "books" is not replace right, so I add one line "p=books " in index.jade,and get books is an array as below:
[com.jade4j.App$1Book@75d837b6, com.jade4j.App$1Book@4631ca2b, com.jade4j.App$1Book@6ecff10d]

it seems just call the default toString() method of Book Class in render?

so, would you tell me how to fix this? and I both try 0.4.4-SNAPSHOT and 0.4.0.

**Comment by schipplock** [comment]
Hey,
you need a public class:

```java
public class Book {
    public String name;
    public double price;
    public Boolean available;

    public Book(String name, double price, Boolean available) {
        this.name = name;
        this.price = price;
        this.available = available;
    }
}
```
and don't put it as an inner class (not working with "public" then, of course :)). I'm using 0.4.3 and it's working fine.

Hope I could help.

Andreas.

**Comment by chbloemer** [comment]
Ok. I close this issue.

**Comment by fengcj** [comment]
@schipplock , thanks you so much.
